repo_name: cicd_demo_2
owner: GreatBat67
project_name: Snowflake Variable-Tier Offering Template
default_branch: dev
branches:
  dev:
    environment: dev
  qa:
    environment: qa
  cicd:
    environment: cicd
  main:
    environment: main
