name: "Standard Tier: Automated Snowflake Delivery - Master"
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    branches:
      - cicd
    paths:
      - 'dcm_automation/**'
      - 'dcm_dbt_cicd/**'
  push:
    branches:
      - cicd
    paths:
      - 'dcm_automation/**'
      - 'dcm_dbt_cicd/**'

permissions:
  id-token: write 
  contents: read

jobs:
  cicd-environment-pipeline:
    if: (github.base_ref == 'cicd' && github.event_name == 'pull_request') || (github.ref_name == 'cicd' && github.event_name == 'push')
    uses: ./.github/workflows/snowflake-pipeline-cicd.yml
    secrets: inherit
